services:
    core:
        hostname: myhostname
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - fleet
        labels:
            - traefik.http.routers.myhostname-localhost.rule=Host(`myhostname.localhost`)
            - traefik.http.services.myhostname-localhost.loadbalancer.server.port=80
            - traefik.http.routers.myhostname-localhost.tls=true
networks:
    sail:
        driver: bridge
    fleet:
        external: true

